schedules:
  - cron: "0 0 * * *"
    displayName: "Nightly Build"
    branches:
      include:
        - 'main'

jobs:
  - template: ./ci.yml
    parameters:
      maxParallel: 1 # any more and we get throttled by AzDO!
      accTest: true
      goVersions:
        - value: '1.24.1'
          ymlSafeName: '1_24_1'

      vmImages:
        - value: 'ubuntu-latest'
          ymlSafeName: ubuntu_latest
